name: Enigma2 CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
    steps:
    - uses: actions/checkout@v2
      run: |
        sudo apt-get -q update
    - name: install prerequisites
      run: |
        sudo apt-get -q update
        sudo apt-get install automake
        sudo apt-get install git
        sudo apt-get install build-essential
        sudo apt-get install gettext
    - name: compile enigma2 python
      run: |
        python -m compileall .
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        echo done!
